### ISSUE TITLE
Npm, Node, babel-plugin-macros links on Babel Macro Page? 

### ISSUE THREAD

**Issue by hagnerd** [sw-yx/babel-blade#15]
I'm not sure if npm, node, and babel-plugin-macros are supposed to be links on the [babel-macro](https://github.com/sw-yx/babel-blade/blob/master/docs/blade-macro.md) page? 

![image](https://user-images.githubusercontent.com/6313764/47126224-2c290280-d24d-11e8-9644-d09171d243c4.png)

**Comment by sw-yx** [comment]
resolved
