### ISSUE TITLE
Support third-party fragments

### ISSUE THREAD

**Issue by jgierer12** [sw-yx/babel-blade#17]
Sometimes, it is necessary to include third-party fragments, such as `gatsby-transform-sharp`s `GatsbyImageSharpFluid` fragment required by the `gatsby-image` component. As far as I can tell, it's currently impossible to use this in a blade-generated query.

**Comment by sw-yx** [comment]
thank you. this one may need some thinking but its not impossible

**Comment by sw-yx** [comment]
got some sample code i can work with?

**Comment by jgierer12** [comment]
Sure, I created a quick example repo to better illustrate the problem: https://github.com/jgierer12/babel-blade-17

I think the implementation of this feature would be trivial, we simply have to add the name of the fragment to the query. But it is incompatible with the current API, since all string parameters after the first one are assumed to be decorators.

If you would be willing to introduce a breaking API change for this, making the second parameter an array of decorators instead would make sense. Otherwise, perhaps something like
```js
data.field(args, ...decorators)(fragment)
```
might work.

**Comment by sw-yx** [comment]
yes i am willing to introduce a breaking API change. this is still early days :)

> But it is incompatible with the current API, since all string parameters after the first one are assumed to be decorators.

actually not true, i think. did you read this somewhere? it used to be the case, but now you can do

```js
data.field('@sort', 'foo: 1', '@delay', 'bar:2')
```

and it'd work out to

```graphql
data {
	field(foo: 1, bar: 2) @sort @delay {
		// ...
	}
}
```

nice, eh?

but it maybe too nice. i'm willing to break that flexibility for a bit more predictability and third party/inline fragments.

in terms of having curried functions like you propose it would introduce extra complexity. i propose this:

```js
data.field(subfields, args, decorators)
```

all three args would take either null, strings, or template strings. subfields include fragments but also any other fields the user doesnt need to actually use in the js at that point in time.

Funny enough, this was the original API design, and i broke it to go for the flexibility which seemed like a good idea at the time. While I originally didnt like asking users to memorize the three arguments (and also putting in `null` for stuff they dont use) it just works better.

**Comment by sw-yx** [comment]
oh lol: https://dev.doctorevidence.com/how-to-write-a-typescript-transform-plugin-fc5308fdd943 i might need to just write a typescript transform...

**Comment by jgierer12** [comment]
> actually not true, i think. did you read this somewhere? it used to be the case, but now you can do

Ah, I didn't know it works like that. That is very cool indeed! I actually don't remember where I got that from, I think you may have said it in the video?

Anyways, I like your proposed API. Being able to manually pass in fields, not just fragments, surely would be useful too in some situations. I suggest all three args can also take arrays of their supported types, so you can for example mix inline fragments and blade-generated ones.

**Comment by sw-yx** [comment]
ah. very interesting. sure thing.

**Comment by sw-yx** [comment]
closing as i am no longer maintaining this - seeking maintainer! https://github.com/sw-yx/babel-blade/issues/23
