### ISSUE TITLE
Allow exporting queries directly

### ISSUE THREAD

**Issue by jgierer12** [sw-yx/babel-blade#18]
```js
import { createQuery } from 'blade.macro';

export const pageQuery = createQuery();

const App = data => {
  const DATA = pageQuery(data);
  const movie = DATA.movie;
};
```

Currently, this throws an error:

```
blade.macro: You can't replace this node, we've already removed it
```

For now, the following workaround is required to do this:

```js
import { createQuery } from 'blade.macro';

const query = createQuery();

export const pageQuery = query;

const App = data => {
  const DATA = query(data);
  const movie = DATA.movie;
};
```

**Comment by sw-yx** [comment]
nice catch! should be an easy one to fix, thankfully. how do you like it otherwise?

**Comment by sw-yx** [comment]
woohoo! https://astexplorer.net/#/gist/01983f61e310f1eaf6b12a221556a937/3515d13c1002ea07af4f8548ddd970079ab32d62

should be releasing in v0.1.5

**Comment by jgierer12** [comment]
Awesome, thanks for the quick fix. I'm a fan of the project so far, but it's not quite production ready. I'll be closely watching it though!

If there are any opportunities to contribute, let me know. I haven't worked with the babel API before, but I'd love to try my hands on a simpler issue.

**Comment by sw-yx** [comment]
haha, yeah its not production ready.

the babel api is pretty big. def read [jamie kyle's handbook](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md) first. that took me a good 2-3 tries before i really got thru all of it. then work on smaller babel plugins that reverse letters or swap out function expressions for arrow function expressions. then read up on kent c dodds' babel macros writing.

i'll be doing a complete ground up typescript rewrite of babel-blade anyway as the bugs have been bothering me too much so i'll be sure to livestream/record that.

**Comment by kentcdodds** [comment]
> i'll be sure to livestream/record that.

💯👍👏

**Comment by sw-yx** [comment]
oh lol: https://dev.doctorevidence.com/how-to-write-a-typescript-transform-plugin-fc5308fdd943 i might need to just write a typescript transform...

babel doesnt seem to have typescript typings which is either an opportunity (a lot of work) or a problem (do we stay in babel and be potentially buggy or make a typescript plugin and alienate js users or maintain both cos we are masochists

**Comment by kentcdodds** [comment]
Please do not opt for a typescript transform....
