### ISSUE TITLE
Support GraphQL template literal tags

### ISSUE THREAD

**Issue by jgierer12** [sw-yx/babel-blade#20]
Many GraphQL clients (e.g. [graphql-tag](https://github.com/apollographql/graphql-tag) or Gatsby's static queries) use a tagged template literal for their queries:

```js
import gql from 'graphql-tag';

export const pageQuery = gql`
  query {
    user(id: 5) {
      firstName
      lastName
    }
  }
`;
```

These implementations currently don't work well with ⛸ . There is a [potential workaround](https://astexplorer.net/#/gist/0658a1f97df3012ff989115e1051f7c0/95205390368eef526ae38b6f43542431f196c3f7), but it isn't compatible with Gatsby, since Gatsby doesn't allow any template string substitutions in its queries.

Solution: Add a way to directly pass the blade output to a template literal tag.

<details>
<summary>Possible syntax ideas</summary>

```js
const query = createQuery();
export const pageQuery = gql`${query}`;
// Simple but misleading (suggests dynamic substitution like in my workaround) 
```

```js
const query = createQuery();
export const pageQuery = gql(query.tagged);
// My personal favorite
```

```js
const query = createTaggedQuery();
export const pageQuery = gql(query);
// Not sure about this one
```

All of these would be transformed into

```js
export const pageQuery = gql`
query query{
  ...
}`;
```
</details>

**Comment by sw-yx** [comment]
heh, i'd previously used `gql(query)` before but looks like this has broken in my recent rewrite. thanks for the ticket. i'll be sure to check that this works with gatsby. will do a rewrite soonish

**Comment by sw-yx** [comment]
closing as i am no longer maintaining this - seeking maintainer! https://github.com/sw-yx/babel-blade/issues/23
