### ISSUE TITLE
Cannot read property 'referencePaths' of undefined

### ISSUE THREAD

**Issue by mastilver** [sw-yx/babel-blade#22]
Hey Shawn, I don't know if you are still working on that, if not that cool, I was just experimenting with it ;)

I think I found an issue, see: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgYQgOzQUwMYwDRwCOArplAJ5wC-cAZlBCHAOTFSEA2zA3AFC_Z0AZ3ggIAN2CYAYlACGAcxCY08ALxxsUTHJgz5SlTAAUzALISpzAJR9BaEXAuTMcDcaQATXXOrW3AHyIvHBw2jBsaHDGIaFwADyoGDgwsXFEpBRqCCRk5MYABrwAkMWhuRRwACqYjghp6Y1iLsGNbY0AdF3OUrKKyqoN7dRDjVT8w6EAJAjNvQYDJuaW-v1GNuNtBdabjdgAFsAcntpo2R5wHBBynpieBN4wvlT-akH1w_aO2kLEHOpwOarQyqYyPOTWCbtcKRaKjdLxTzAcSaDhyIRCABycmUagAREC8QF4Y0EFcbnc3GoNLQ5BwhK4APxwyaNeJgAIAGWuSLQCniAHoOST0v4AFws1lxRHI4lStn7ABMAQQPz-MA6QI6MGAMA4mCogqVcvl0o5qtq6s1Kw6clw0CEHV-YEgsGAfMNQpNpoS5rV_2tLlt9qgjv1N3dCk9wp9gqR4m9kx2IoSAvjidFfDaVF2oQFJshVD4QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.6.3&externalPlugins=babel-plugin-blade%400.1.11

Removing line 14 removes the error
Am I allowed to use fragments here?

Is this related to #20 ?

**Comment by sw-yx** [comment]
hmm, yes fragments are supposed to be supported. but i dont think you're using it in the way i intended haha - see the test https://github.com/sw-yx/babel-blade/blob/master/packages/babel-plugin-blade/src/__tests__/fixtures/fragment.js

anyway, you're right, im not really working on this anymore. i'll put up a notice.

**Comment by sw-yx** [comment]
https://github.com/sw-yx/babel-blade/issues/23

**Comment by mastilver** [comment]
NP, given my open source track record I will try not to take on this project :D

But if I start using it seriously, I might come back to you
